
import { Dog } from './types';

export const DOGS: Dog[] = [
  {
    id: '1',
    name: 'Luna',
    breed: 'Golden Retriever',
    age: 'Young',
    size: 'Large',
    energyLevel: 'High',
    weight: '62 lbs',
    color: 'Cream',
    description: 'Luna is a joyful bundle of energy who loves long walks on the beach and fetching tennis balls. She is incredibly gentle with children and highly social with other dogs. She thrives in active environments.',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=800',
    tags: ['Friendly', 'Active', 'Smart', 'Water-lover'],
    location: 'San Francisco, CA',
    gender: 'Female',
    compatibility: { cats: true, dogs: true, kids: true }
  },
  {
    id: '2',
    name: 'Cooper',
    breed: 'Corgi',
    age: 'Adult',
    size: 'Small',
    energyLevel: 'Moderate',
    weight: '28 lbs',
    color: 'Sable',
    description: 'Cooper is a dignified gentleman with a playful streak. He enjoys calm environments and short strolls. He is looking for a cozy home where he can be the center of attention.',
    imageUrl: 'https://images.unsplash.com/photo-1519098901909-b1553a1190af?auto=format&fit=crop&q=80&w=800',
    tags: ['Cuddly', 'Calm', 'Loyal', 'Apartment-friendly'],
    location: 'Portland, OR',
    gender: 'Male',
    compatibility: { cats: false, dogs: true, kids: true }
  },
  {
    id: '3',
    name: 'Willow',
    breed: 'Australian Shepherd',
    age: 'Puppy',
    size: 'Medium',
    energyLevel: 'Very High',
    weight: '18 lbs',
    color: 'Blue Merle',
    description: 'A brilliant puppy who needs a job to do. Willow is incredibly smart and quick to learn. She thrives on mental stimulation and vigorous physical activity.',
    imageUrl: 'https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?auto=format&fit=crop&q=80&w=800',
    tags: ['Intelligent', 'Fast', 'Eager', 'Working-dog'],
    location: 'Seattle, WA',
    gender: 'Female',
    compatibility: { cats: true, dogs: true, kids: true }
  },
  {
    id: '4',
    name: 'Bear',
    breed: 'Great Pyrenees Mix',
    age: 'Senior',
    size: 'Extra Large',
    energyLevel: 'Low',
    weight: '105 lbs',
    color: 'White',
    description: 'Bear is a gentle giant who spends most of his day napping in the sun. He is perfect for a low-energy household looking for a steady, loving companion.',
    imageUrl: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&q=80&w=800',
    tags: ['Gentle', 'Quiet', 'Patient', 'Protective'],
    location: 'Denver, CO',
    gender: 'Male',
    compatibility: { cats: true, dogs: false, kids: true }
  },
  {
    id: '5',
    name: 'Piper',
    breed: 'Border Collie',
    age: 'Young',
    size: 'Medium',
    energyLevel: 'High',
    weight: '42 lbs',
    color: 'Black & White',
    description: 'Piper is the ultimate frisbee partner. She is agile, responsive, and always ready for the next adventure. She requires an active owner who loves being outdoors.',
    imageUrl: 'https://images.unsplash.com/photo-1553736026-ff14d158d222?auto=format&fit=crop&q=80&w=800',
    tags: ['Athletic', 'Focused', 'Protective', 'Agility'],
    location: 'Austin, TX',
    gender: 'Female',
    compatibility: { cats: false, dogs: true, kids: false }
  },
  {
    id: '6',
    name: 'Finn',
    breed: 'French Bulldog',
    age: 'Adult',
    size: 'Small',
    energyLevel: 'Low',
    weight: '24 lbs',
    color: 'Fawn',
    description: 'Finn is a charismatic little guy who loves city living. He is content with short walks and plenty of couch time. He has a big personality in a small package.',
    imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=800',
    tags: ['Funny', 'Charming', 'Relaxed', 'City-pup'],
    location: 'New York, NY',
    gender: 'Male',
    compatibility: { cats: true, dogs: true, kids: true }
  }
];
